### PR TITLE
Add support to integers through input

### PR DESCRIPTION
**Pull request by georgewoodall82**
Automatically sets variable type to an integer if a number is entered into input()

This fixes issue #2

### CODE REVIEW

**Comment by SinaKhalili** [comment]
Lovely, thanks for doing this! 
If it's not too much work could you please add a sample program to the `sample_programs` folder demonstrating this? Maybe @ferdibaum can help?

**Comment by georgewoodall82** [comment]
I added an addition sample that can add two strings together or two integers.

**Comment by SinaKhalili** [comment]
Awesome, merged!

**Comment by SinaKhalili** [comment]
I'll try to get a github action going for releasing it back to PyPI so the world may enjoy

**Pull request merged**
